image: maven:3.6.1-jdk-8

pipelines:
  # runs on all builds on any branch. Unit tests to run here?
  default: 
    - step:
        name: Sonar Analysis
        script: 
          - echo "Sonar not currently configured in cloud environment"
  branches:
    # we only deploy from bitbucketmaster
    bitbucketmaster: 
      # First step cannot be manual
      - step:
          name: Capture IP For Diagnostics
          caches:
            - maven
          script: 
            - curl -4 https://ifconfig.co/ 
            - pwd
            - ls  

      #########################   
      # Staging COM
      #########################
      - step:
          name: COM Stage Build Author
          trigger: manual
          deployment: com-stage-author
          caches:
           - maven
          script:
            - cd silversea-aem-parent && mvn clean install 
            - cd silversea-com && mvn --settings ../maven-settings-ci.xml clean install -Pauto-install-package -Dcq.password=$AUTHOR_STAGE_PASSWORD -Dcq.user=ci-user -Dcq.url=http://18.204.183.84:4502 -DapiClientVersion="[3.0, 4.0]"
      - step:
          name: COM Stage Build Publish 1
          trigger: manual
          deployment: com-stage-publish-1
          caches:
           - maven
          script:
            - cd silversea-com
            - mvn --settings ../maven-settings-ci.xml -f ../parent-fetcher-pom.xml dependency:get -Dartifact=com.silversea.aem:silversea-aem-parent:1.5.1 -DremoteRepositories=s3.release -Dpackaging=pom -DapiClientVersion="[3.0, 4.0]" 
            - mvn --settings ../maven-settings-ci.xml clean install -Pauto-install-package -Dcq.password=$AUTHOR_STAGE_PASSWORD -Dcq.user=ci-user -Dcq.url=http://18.234.4.77:4503 -DapiClientVersion="[3.0, 4.0]"
      - step:
          name: COM Stage Build Publish 2
          trigger: manual
          deployment: com-stage-publish-2
          caches:
           - maven
          script:
            - cd silversea-com
            - mvn --settings ../maven-settings-ci.xml -f ../parent-fetcher-pom.xml dependency:get -Dartifact=com.silversea.aem:silversea-aem-parent:1.5.1 -DremoteRepositories=s3.release -Dpackaging=pom -DapiClientVersion="[3.0, 4.0]"
            - mvn --settings ../maven-settings-ci.xml clean install -Pauto-install-package -Dcq.password=$AUTHOR_STAGE_PASSWORD -Dcq.user=ci-user -Dcq.url=http://35.173.158.72:4503 -DapiClientVersion="[3.0, 4.0]"

      #########################   
      # Staging SSC
      #########################
      - step:
          name: SSC Stage Build Author
          trigger: manual
          caches:
           - maven
          script:
            - cd silversea-ssc 
            - mvn --settings ../maven-settings-ci.xml -f ../parent-fetcher-pom.xml dependency:get -Dartifact=com.silversea.aem:silversea-aem-parent:1.5.1 -DremoteRepositories=s3.release -Dpackaging=pom -DapiClientVersion="[3.0, 4.0]"
            - mvn --settings ../maven-settings-ci.xml clean install -Pauto-install-package -Dcq.password=$AUTHOR_STAGE_PASSWORD -Dcq.user=ci-user -Dcq.url=http://18.204.183.84:4502 -DapiClientVersion="[3.0, 4.0]"
      - step:
          name: SSC Stage Build Publish 1
          trigger: manual
          caches:
           - maven
          script:
            - cd silversea-ssc
            - mvn --settings ../maven-settings-ci.xml -f ../parent-fetcher-pom.xml dependency:get -Dartifact=com.silversea.aem:silversea-aem-parent:1.5.1 -DremoteRepositories=s3.release -Dpackaging=pom -DapiClientVersion="[3.0, 4.0]" 
            - mvn --settings ../maven-settings-ci.xml clean install -Pauto-install-package -Dcq.password=$AUTHOR_STAGE_PASSWORD -Dcq.user=ci-user -Dcq.url=http://18.234.4.77:4503 -DapiClientVersion="[3.0, 4.0]"
      - step:
          name: SSC Stage Build Publish 2
          trigger: manual
          caches:
           - maven
          script:
            - cd silversea-ssc
            - mvn --settings ../maven-settings-ci.xml -f ../parent-fetcher-pom.xml dependency:get -Dartifact=com.silversea.aem:silversea-aem-parent:1.5.1 -DremoteRepositories=s3.release -Dpackaging=pom -DapiClientVersion="[3.0, 4.0]"
            - mvn --settings ../maven-settings-ci.xml clean install -Pauto-install-package -Dcq.password=$AUTHOR_STAGE_PASSWORD -Dcq.user=ci-user -Dcq.url=http://35.173.158.72:4503 -DapiClientVersion="[3.0, 4.0]"      


      # Production
      - step:
          name: COM Prod Build Author
          trigger: manual
          deployment: prod-author
          caches:
           - maven
          script:
            - cd silversea-com
            - mvn --settings ../maven-settings-ci.xml -f ../parent-fetcher-pom.xml dependency:get -Dartifact=com.silversea.aem:silversea-aem-parent:1.5.1 -DremoteRepositories=s3.release -Dpackaging=pom -DapiClientVersion="[3.0, 4.0]"
            - mvn --settings ../maven-settings-ci.xml clean install -Pauto-install-package -Dcq.password=$AUTHOR_PROD_PASSWORD -Dcq.user=ci-user -Dcq.url=http://18.211.58.161:4502 -DapiClientVersion="[3.0, 4.0]"
      - step:
          name: COM Prod Build Publish 1
          trigger: manual
          deployment: prod-publish-1
          caches:
           - maven
          script:
            - cd silversea-com
            - mvn --settings ../maven-settings-ci.xml -f ../parent-fetcher-pom.xml dependency:get -Dartifact=com.silversea.aem:silversea-aem-parent:1.5.1 -DremoteRepositories=s3.release -Dpackaging=pom -DapiClientVersion="[3.0, 4.0]"
            - mvn --settings ../maven-settings-ci.xml clean install -Pauto--Daws.key=$ARTIFACTS_USER -Daws.secret=$ARTIFACTS_PASSWORD -DapiClientVersion="[3.0, 4.0]"
      - step:
          name: COM Prod Build Publish 2
          trigger: manual
          deployment: prod-publish-2
          caches:
           - maven
          script:
            - cd silversea-com
            - mvn --settings ../maven-settings-ci.xml -f ../parent-fetcher-pom.xml dependency:get -Dartifact=com.silversea.aem:silversea-aem-parent:1.5.1 -DremoteRepositories=s3.release -Dpackaging=pom -DapiClientVersion="[3.0, 4.0]" 
            - mvn --settings ../maven-settings-ci.xml clean install -Pauto-install-package -Dcq.password=$AUTHOR_PROD_PASSWORD -Dcq.user=ci-user -Dcq.url=http://18.214.75.8:4503 -DapiClientVersion="[3.0, 4.0]"            