image: maven:3.6.1-jdk-8

definitions:
  caches:
    mvn1: maven

pipelines:
  # runs on all builds on any branch. Unit tests to run here?
  default: 
    - step:
        name: Sonar Analysis
        script: 
          - echo "Sonar not currently configured in cloud environment"
  branches:
    # we only deploy from bitbucketmaster
    bitbucketmaster: 
      # First step cannot be manual
      - step:
          name: Capture IP For Diagnostics
          script: 
            - curl -4 https://ifconfig.co/           
      - step:
          name: Publish Artifact # ssc depends on silversea-com-core
          trigger: manual
          caches:
            - mvn1
          script:
            - mvn --settings maven-settings-ci.xml -f pom2.xml dependency:get -Dartifact=com.silversea.aem:silversea-aem-parent:1.5.1 -DremoteRepositories=s3.release -Dpackaging=pom -Daws.key=$ARTIFACTS_USER -Daws.secret=$ARTIFACTS_PASSWORD
            - mvn --settings maven-settings-ci.xml install -Daws.key=$ARTIFACTS_USER -Daws.secret=$ARTIFACTS_PASSWORD
            - mvn --settings maven-settings-ci.xml deploy -Daws.key=$ARTIFACTS_USER -Daws.secret=$ARTIFACTS_PASSWORD
      # Staging
      - step:
          name: Stage Build Author
          trigger: manual
          deployment: stage-author
          caches:
           - mvn1
          script:
            - mvn --settings maven-settings-ci.xml -f pom2.xml dependency:get -Dartifact=com.silversea.aem:silversea-aem-parent:1.5.1 -DremoteRepositories=s3.release -Dpackaging=pom -Daws.key=$ARTIFACTS_USER -Daws.secret=$ARTIFACTS_PASSWORD
            - mvn --settings maven-settings-ci.xml clean install -Pauto-install-package -Dcq.password=$AUTHOR_STAGE_PASSWORD -Dcq.user=ci-user -Dcq.url=http://18.204.183.84:4502 -Daws.key=$ARTIFACTS_USER -Daws.secret=$ARTIFACTS_PASSWORD 
      - step:
          name: Stage Build Publish 1
          trigger: manual
          deployment: stage-publish-1
          caches:
           - mvn1
          script:
            - mvn --settings maven-settings-ci.xml -f pom2.xml dependency:get -Dartifact=com.silversea.aem:silversea-aem-parent:1.5.1 -DremoteRepositories=s3.release -Dpackaging=pom -Daws.key=$ARTIFACTS_USER -Daws.secret=$ARTIFACTS_PASSWORD
            - mvn --settings maven-settings-ci.xml clean install -Pauto-install-package -Dcq.password=$AUTHOR_STAGE_PASSWORD -Dcq.user=ci-user -Dcq.url=http://18.234.4.77:4503 -Daws.key=$ARTIFACTS_USER -Daws.secret=$ARTIFACTS_PASSWORD
      - step:
          name: Stage Build Publish 2
          trigger: manual
          deployment: stage-publish-2
          caches:
           - mvn1
          script:
            - mvn --settings maven-settings-ci.xml -f pom2.xml dependency:get -Dartifact=com.silversea.aem:silversea-aem-parent:1.5.1 -DremoteRepositories=s3.release -Dpackaging=pom -Daws.key=$ARTIFACTS_USER -Daws.secret=$ARTIFACTS_PASSWORD
            - mvn --settings maven-settings-ci.xml clean install -Pauto-install-package -Dcq.password=$AUTHOR_STAGE_PASSWORD -Dcq.user=ci-user -Dcq.url=http://35.173.158.72:4503 -Daws.key=$ARTIFACTS_USER -Daws.secret=$ARTIFACTS_PASSWORD
      # Production
      - step:
          name: Prod Build Author
          trigger: manual
          deployment: prod-author
          #caches:
          # - maven
          script:
            - mvn --settings maven-settings-ci.xml -f pom2.xml dependency:get -Dartifact=com.silversea.aem:silversea-aem-parent:1.5.1 -DremoteRepositories=s3.release -Dpackaging=pom -Daws.key=$ARTIFACTS_USER -Daws.secret=$ARTIFACTS_PASSWORD
            - mvn --settings maven-settings-ci.xml clean install -Pauto-install-package -Dcq.password=$AUTHOR_PROD_PASSWORD -Dcq.user=ci-user -Dcq.url=http://18.211.58.161:4502 -Daws.key=$ARTIFACTS_USER -Daws.secret=$ARTIFACTS_PASSWORD
      - step:
          name: Prod Build Publish 1
          trigger: manual
          deployment: prod-publish-1
          caches:
           - mvn1
          script:
            - mvn --settings maven-settings-ci.xml -f pom2.xml dependency:get -Dartifact=com.silversea.aem:silversea-aem-parent:1.5.1 -DremoteRepositories=s3.release -Dpackaging=pom -Daws.key=$ARTIFACTS_USER -Daws.secret=$ARTIFACTS_PASSWORD
            - mvn --settings maven-settings-ci.xml clean install -Pauto-install-package -Dcq.password=$AUTHOR_PROD_PASSWORD -Dcq.user=ci-user -Dcq.url=http://35.168.37.187:4503 -Daws.key=$ARTIFACTS_USER -Daws.secret=$ARTIFACTS_PASSWORD
      - step:
          name: Prod Build Publish 2
          trigger: manual
          deployment: prod-publish-2
          caches:
           - mvn1
          script:
           - mvn --settings maven-settings-ci.xml -f pom2.xml dependency:get -Dartifact=com.silversea.aem:silversea-aem-parent:1.5.1 -DremoteRepositories=s3.release -Dpackaging=pom -Daws.key=$ARTIFACTS_USER -Daws.secret=$ARTIFACTS_PASSWORD
           - mvn --settings maven-settings-ci.xml clean install -Pauto-install-package -Dcq.password=$AUTHOR_PROD_PASSWORD -Dcq.user=ci-user -Dcq.url=http://18.214.75.8:4503 -Daws.key=$ARTIFACTS_USER -Daws.secret=$ARTIFACTS_PASSWORD            