image: maven:3.6.1-jdk-8

pipelines:
  # runs on all builds on any branch
  default: 
    - step:
        name: Build and Test
        caches:
          - maven
        script: 
          - ./build_and_test_local.sh
  branches:
    # we only deploy from bitbucketmaster
    bitbucketmaster: 
      # First step cannot be manual
      - step:
          name: Build and Test
          caches:
            - maven
          script: 
            - ./build_and_test_local.sh 

      #########################   
      # Staging
      #########################
      - step:
          name: Stage Build Author
          trigger: manual
          deployment: stage-author
          caches:
            - maven
          script:
            - ./build_and_deploy.sh http://18.204.183.84:4502 $AUTHOR_STAGE_PASSWORD silversea-admin "${BITBUCKET_BUILD_NUMBER}"
      - step:
          name: Stage Build Publish 1
          trigger: manual
          deployment: stage-publish-1
          caches:
            - maven
          script:
            - ./build_and_deploy.sh http://18.234.4.77:4503 $AUTHOR_STAGE_PASSWORD silversea-admin "${BITBUCKET_BUILD_NUMBER}"
      - step:
          name: Stage Build Publish 2
          trigger: manual
          deployment: stage-publish-2
          caches:
            - maven
          script:
            - ./build_and_deploy.sh http://35.173.158.72:4503 $AUTHOR_STAGE_PASSWORD silversea-admin "${BITBUCKET_BUILD_NUMBER}"   
      #########################   
      # Prod
      #########################
      - step:
          name: Prod Build Author
          trigger: manual
          deployment: prod-author
          caches:
            - maven
          script:
            - ./build_and_deploy.sh http://18.211.58.161:4502 $AUTHOR_PROD_PASSWORD silversea-admin "${BITBUCKET_BUILD_NUMBER}"
      - step:
          name: Prod Build Publish 1
          trigger: manual
          deployment: prod-publish-1
          caches:
            - maven
          script:
            - ./build_and_deploy.sh http://35.168.37.187:4503 $AUTHOR_PROD_PASSWORD silversea-admin "${BITBUCKET_BUILD_NUMBER}"
      - step:
          name: Prod Build Publish 2
          trigger: manual
          deployment: prod-publish-2
          caches:
            - maven
          script:
            - ./build_and_deploy.sh http://18.214.75.8:4503 $AUTHOR_PROD_PASSWORD silversea-admin "${BITBUCKET_BUILD_NUMBER}"