version: '3.7'
services:
  silversea:
    image: maven:3.6.1-jdk-8
    container_name: silverseacom
    command: ["sleep", "infinity"]
    working_dir: /code
    volumes:
      - type: bind
        source: .
        target: /code
        volume:
          nocopy: true
        consistency: cached 
      - type: volume
        source: maven-cache
        target: /root/.m2
    environment:
     - AEM_HOST=host.docker.internal

# These volumess will be persisted
volumes:
  maven-cache: