package com.silversea.aem.ws;

import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-09T17:59:42.018+01:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "LeadFromWeb03HttpPost")
@XmlSeeAlso({ObjectFactory.class})
public interface LeadFromWeb03HttpPost {
}
