package com.silversea.aem.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-09T17:59:41.967+01:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "LeadFromWeb03Soap")
@XmlSeeAlso({ObjectFactory.class})
public interface LeadFromWeb03Soap {

    @WebMethod(action = "http://tempuri.org/New Method with 52 Arguments")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "New_x0020_Method_x0020_with_x0020_52_x0020_ArgumentsResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    public NewX0020MethodX0020WithX002052X0020ArgumentsResponse addRequest(
        @WebParam(partName = "parameters", name = "New_x0020_Method_x0020_with_x0020_52_x0020_Arguments", targetNamespace = "http://tempuri.org/")
        NewX0020MethodX0020WithX002052X0020Arguments parameters
    );

    @WebMethod(action = "http://tempuri.org/addRequestObj")
    @RequestWrapper(localName = "addRequestObj", targetNamespace = "http://tempuri.org/", className = "com.silversea.aem.ws.AddRequestObj")
    @ResponseWrapper(localName = "addRequestObjResponse", targetNamespace = "http://tempuri.org/", className = "com.silversea.aem.ws.AddRequestObjResponse")
    @WebResult(name = "addRequestObjResult", targetNamespace = "http://tempuri.org/")
    public int addRequestObj(
        @WebParam(name = "item", targetNamespace = "http://tempuri.org/")
        com.silversea.aem.ws.RequestItem03 item
    );
}
