/*
 * APIv3
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * LandSimple
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-13T10:46:18.788Z")
public class LandSimple {
  @SerializedName("land_id")
  private Integer landId = null;

  @SerializedName("land_url")
  private String landUrl = null;

  public LandSimple landId(Integer landId) {
    this.landId = landId;
    return this;
  }

   /**
   * Get landId
   * @return landId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getLandId() {
    return landId;
  }

  public void setLandId(Integer landId) {
    this.landId = landId;
  }

  public LandSimple landUrl(String landUrl) {
    this.landUrl = landUrl;
    return this;
  }

   /**
   * Get landUrl
   * @return landUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLandUrl() {
    return landUrl;
  }

  public void setLandUrl(String landUrl) {
    this.landUrl = landUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LandSimple landSimple = (LandSimple) o;
    return Objects.equals(this.landId, landSimple.landId) &&
        Objects.equals(this.landUrl, landSimple.landUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(landId, landUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LandSimple {\n");
    
    sb.append("    landId: ").append(toIndentedString(landId)).append("\n");
    sb.append("    landUrl: ").append(toIndentedString(landUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

