/*
 * APIv3
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.VoyagePriceMarket;
import io.swagger.client.model.VoyageWithItinerary;
import java.util.ArrayList;
import java.util.List;

/**
 * SpecialVoyage
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-13T10:46:18.788Z")
public class SpecialVoyage {
  @SerializedName("special_voyage_id")
  private String specialVoyageId = null;

  @SerializedName("special_voyage_name")
  private String specialVoyageName = null;

  @SerializedName("voyages")
  private List<VoyageWithItinerary> voyages = new ArrayList<VoyageWithItinerary>();

  @SerializedName("prices")
  private List<VoyagePriceMarket> prices = new ArrayList<VoyagePriceMarket>();

  public SpecialVoyage specialVoyageId(String specialVoyageId) {
    this.specialVoyageId = specialVoyageId;
    return this;
  }

   /**
   * Get specialVoyageId
   * @return specialVoyageId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSpecialVoyageId() {
    return specialVoyageId;
  }

  public void setSpecialVoyageId(String specialVoyageId) {
    this.specialVoyageId = specialVoyageId;
  }

  public SpecialVoyage specialVoyageName(String specialVoyageName) {
    this.specialVoyageName = specialVoyageName;
    return this;
  }

   /**
   * Get specialVoyageName
   * @return specialVoyageName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSpecialVoyageName() {
    return specialVoyageName;
  }

  public void setSpecialVoyageName(String specialVoyageName) {
    this.specialVoyageName = specialVoyageName;
  }

  public SpecialVoyage voyages(List<VoyageWithItinerary> voyages) {
    this.voyages = voyages;
    return this;
  }

  public SpecialVoyage addVoyagesItem(VoyageWithItinerary voyagesItem) {
    this.voyages.add(voyagesItem);
    return this;
  }

   /**
   * Get voyages
   * @return voyages
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<VoyageWithItinerary> getVoyages() {
    return voyages;
  }

  public void setVoyages(List<VoyageWithItinerary> voyages) {
    this.voyages = voyages;
  }

  public SpecialVoyage prices(List<VoyagePriceMarket> prices) {
    this.prices = prices;
    return this;
  }

  public SpecialVoyage addPricesItem(VoyagePriceMarket pricesItem) {
    this.prices.add(pricesItem);
    return this;
  }

   /**
   * Get prices
   * @return prices
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<VoyagePriceMarket> getPrices() {
    return prices;
  }

  public void setPrices(List<VoyagePriceMarket> prices) {
    this.prices = prices;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpecialVoyage specialVoyage = (SpecialVoyage) o;
    return Objects.equals(this.specialVoyageId, specialVoyage.specialVoyageId) &&
        Objects.equals(this.specialVoyageName, specialVoyage.specialVoyageName) &&
        Objects.equals(this.voyages, specialVoyage.voyages) &&
        Objects.equals(this.prices, specialVoyage.prices);
  }

  @Override
  public int hashCode() {
    return Objects.hash(specialVoyageId, specialVoyageName, voyages, prices);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpecialVoyage {\n");
    
    sb.append("    specialVoyageId: ").append(toIndentedString(specialVoyageId)).append("\n");
    sb.append("    specialVoyageName: ").append(toIndentedString(specialVoyageName)).append("\n");
    sb.append("    voyages: ").append(toIndentedString(voyages)).append("\n");
    sb.append("    prices: ").append(toIndentedString(prices)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

