/*
 * APIv3
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.VoyagePriceMarket;
import java.util.ArrayList;
import java.util.List;

/**
 * VoyagePriceComplete
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-13T10:46:18.788Z")
public class VoyagePriceComplete {
  @SerializedName("voyage_id")
  private Integer voyageId = null;

  @SerializedName("voyage_cod")
  private String voyageCod = null;

  @SerializedName("voyage_url")
  private String voyageUrl = null;

  @SerializedName("market_currency")
  private List<VoyagePriceMarket> marketCurrency = new ArrayList<VoyagePriceMarket>();

  public VoyagePriceComplete voyageId(Integer voyageId) {
    this.voyageId = voyageId;
    return this;
  }

   /**
   * Get voyageId
   * @return voyageId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getVoyageId() {
    return voyageId;
  }

  public void setVoyageId(Integer voyageId) {
    this.voyageId = voyageId;
  }

  public VoyagePriceComplete voyageCod(String voyageCod) {
    this.voyageCod = voyageCod;
    return this;
  }

   /**
   * Get voyageCod
   * @return voyageCod
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVoyageCod() {
    return voyageCod;
  }

  public void setVoyageCod(String voyageCod) {
    this.voyageCod = voyageCod;
  }

  public VoyagePriceComplete voyageUrl(String voyageUrl) {
    this.voyageUrl = voyageUrl;
    return this;
  }

   /**
   * Get voyageUrl
   * @return voyageUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getVoyageUrl() {
    return voyageUrl;
  }

  public void setVoyageUrl(String voyageUrl) {
    this.voyageUrl = voyageUrl;
  }

  public VoyagePriceComplete marketCurrency(List<VoyagePriceMarket> marketCurrency) {
    this.marketCurrency = marketCurrency;
    return this;
  }

  public VoyagePriceComplete addMarketCurrencyItem(VoyagePriceMarket marketCurrencyItem) {
    this.marketCurrency.add(marketCurrencyItem);
    return this;
  }

   /**
   * Get marketCurrency
   * @return marketCurrency
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<VoyagePriceMarket> getMarketCurrency() {
    return marketCurrency;
  }

  public void setMarketCurrency(List<VoyagePriceMarket> marketCurrency) {
    this.marketCurrency = marketCurrency;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VoyagePriceComplete voyagePriceComplete = (VoyagePriceComplete) o;
    return Objects.equals(this.voyageId, voyagePriceComplete.voyageId) &&
        Objects.equals(this.voyageCod, voyagePriceComplete.voyageCod) &&
        Objects.equals(this.voyageUrl, voyagePriceComplete.voyageUrl) &&
        Objects.equals(this.marketCurrency, voyagePriceComplete.marketCurrency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(voyageId, voyageCod, voyageUrl, marketCurrency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VoyagePriceComplete {\n");
    
    sb.append("    voyageId: ").append(toIndentedString(voyageId)).append("\n");
    sb.append("    voyageCod: ").append(toIndentedString(voyageCod)).append("\n");
    sb.append("    voyageUrl: ").append(toIndentedString(voyageUrl)).append("\n");
    sb.append("    marketCurrency: ").append(toIndentedString(marketCurrency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

